#!/bin/bash
if [ $# -lt 1 ]; then
  echo 1>&2 "$0: not enough arguments"
  exit 2
elif [ $# -gt 1 ]; then
  echo 1>&2 "$0: too many arguments"
  exit 2
fi

green=$'\e[1;32m'
red=$'\e[1;31m'
clear=$'\033[0m'

mac_unformatted=$(echo "$1"| tr '[:upper:]' '[:lower:]' | sed 's/://g' | sed 's/-//g' | sed 's/\.//g' | tr -d [:f-z)

if [ ${#mac_unformatted} -ne 12 ]; then
echo "Argument ${red}${1}${clear} is invalid"
exit 128
fi

mac_hyphen=$(echo "$mac_unformatted" | sed 's/\(..\)/\1-/g;s/-$//' )

mac_colon=$(echo "$mac_unformatted" | sed 's/\(..\)/\1:/g;s/:$//' )

mac_period=$(echo "$mac_unformatted" | sed 's/\(....\)/\1./g;s/.$//' )

echo "Hyphen Notation: ${green}${mac_hyphen}${clear}"
echo "Colon Notation:  ${green}$mac_colon${clear}"
echo "Period Notation: ${green}$mac_period${clear}"
