#!/bin/bash
#By Austin Pack
#Created 11/10/2021

if [ $# -lt 1 ]; then
  echo 1>&2 "$0: not enough arguments"
  exit 2
elif [ $# -gt 1 ]; then
  echo 1>&2 "$0: too many arguments"
  exit 2
fi

#Color codes to use for the output
green=$'\e[1;32m'
red=$'\e[1;31m'
clear=$'\033[0m'

#Make the argument a hexadecimal string without special characters or characters g-z
mac_unformatted=$(echo "$1"| tr '[:upper:]' '[:lower:]' | tr -dc '[:xdigit:]' | tr -d 'g-z')

#If the mac is too short or too long the argument is invalid
if [ ${#mac_unformatted} -ne 12 ]; then
echo "Argument ${red}${1}${clear} is invalid"
exit 128
fi

#Format the mac into the different notations
mac_hyphen=$(echo "$mac_unformatted" | sed 's/\(..\)/\1-/g;s/-$//' )
mac_colon=$(echo "$mac_unformatted" | sed 's/\(..\)/\1:/g;s/:$//' )
mac_period=$(echo "$mac_unformatted" | sed 's/\(....\)/\1./g;s/.$//' )

#Output all of the notations
echo "Hyphen Notation: ${green}${mac_hyphen}${clear}"
echo "Colon Notation:  ${green}$mac_colon${clear}"
echo "Period Notation: ${green}$mac_period${clear}"
